language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=4.1

install:
  - nvm install $NODE_VERSION
  - npm install

script:
  - nvm use $NODE_VERSION
  - npm run cover

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/caa35ceb4dd217d50b26
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
